### ISSUE TITLE
Question regarding aarch64 for rPi

### ISSUE THREAD

**Issue by johncblacker** [ltekieli/bazel_cross_compile#1]
Is the aarch64 toolchain compatible with the raspberry pi 3b+ 32-bit?  If not, what toolchain should I be using to cross-build for that platform?

**Comment by ltekieli** [comment]
Hi, it is not. You can generate your own toolchain using https://crosstool-ng.github.io/. And if you are not building your system from scratch you can download preconfigured toolchains and then use the sysroot from your OS for building.
