### ISSUE TITLE
cross-compile gcc 6.5.0 build fail

### ISSUE THREAD

**Issue by wssbygone** [ltekieli/bazel_cross_compile#6]
hello, 
      I am working on Ubuntu 18.04, arch x86_64,  doing the cross-compiling with bazel,  and  cross-compile GCC version is 6.5.0,  below is the log:
Execution platform: @local_config_platform//:host
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/opt/gcc-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/6.5.0/../../../../aarch64-linux-gnu/bin/ld: cannot find /lib/libc.so.6
/opt/gcc-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/6.5.0/../../../../aarch64-linux-gnu/bin/ld: cannot find /usr/lib/libc_nonshared.a
/opt/gcc-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/6.5.0/../../../../aarch64-linux-gnu/bin/ld: cannot find /lib/ld-linux-aarch64.so.1

and I can find those libs existed under sysroots, 
/opt/sysroots/lib/libc.so.6
/opt/sysroots/usr/lib/libc_nonshared.a
/opt/sysroots/lib/ld-linux-aarch64.so.1

The flags  in default_compiler_flags  and default_linker_flags  are the same as the sample configurations: 
"--sysroot=external/aarch64-linux-gnu-sysroot", 

and below is the  sysroots path config:
if "aarch64-linux-gnu-sysroot" not in native.existing_rules():
    native.new_local_repository(
        name = "aarch64-linux-gnu-sysroot",
        path = "/opt/sysroots",
        build_file = "//bazel/toolchain/aarch64-linux-gnu:aarch64-linux-gnu-sysroot.BUILD",
  ) 

I will very appreciate if anyone could give me a hint.

**Comment by ltekieli** [comment]
I could take a look if you provide a docker image (or Dockerfile) with your setup and the code for setting up the toolchain.

**Comment by wssbygone** [comment]
hi  Itekieli， I fix the bug, look at this link https://stackoverflow.com/questions/52386530/linker-fails-in-sandbox-when-running-through-bazel-but-works-when-sandboxed-comm
, thank you all the same.
