### ISSUE TITLE
how to configure the yocto toolchain with bazel platform?

### ISSUE THREAD

**Issue by damonChenzf07** [ltekieli/bazel_cross_compile#7]
HI:
I have a yocoto toolchain , and I want to use this toolchain with bazel platform to cross compile my app to the target board.
I follow the 04_platforms sample, I got a link error:
```
root@Zdrive:/home/root/Work/Codes/bazel_cross_compile/04_platforms# **bazel build -s --config=s32g-platform //:hello**
INFO: Analyzed target //:hello (71 packages loaded, 24732 targets configured).
ERROR: /home/root/Work/Codes/bazel_cross_compile/04_platforms/BUILD:7:10: Linking hello failed: error reading file '@@aarch64-fsl-linux//:etc/ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem': **/root/.cache/bazel/_bazel_root/070a2d845f91c9901923bd1aab12f574/external/aarch64-fsl-linux/etc/ssl/certs/NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem (No such file or directory)**
ERROR: /home/root/Work/Codes/bazel_cross_compile/04_platforms/BUILD:7:10**: Linking hello failed: 1 input file(s) are in error
Target //:hello failed to build**
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/root/Work/Codes/bazel_cross_compile/04_platforms/BUILD:7:10 Linking hello failed: 1 input file(s) are in error
INFO: Elapsed time: 0.655s, Critical Path: 0.00s
INFO: 5 processes: 5 internal.
ERROR: Build did NOT complete successfully
```

But I check this file, it does here: 
```
ERROR: Build did NOT complete successfully
úsítvány.pem home/root/Work/Codes/bazel_cross_compile/04_platforms# ls /root/.cache/bazel/_bazel_root/070a2d845f91c9901923bd1aab12f574/external/aarch64-fsl-linux/etc/ssl/certs/NetLock_Arany_\=Class_Gold\=_Főtan�
'/root/.cache/bazel/_bazel_root/070a2d845f91c9901923bd1aab12f574/external/aarch64-fsl-linux/etc/ssl/certs/NetLock_Arany_=Class_Gold=_F'$'\305\221''tan'$'\303\272''s'$'\303\255''tv'$'\303\241''ny.pem'
root@Zdrive:/home/root/Work/Codes/bazel_cross_compile/04_platforms# 
```

It looks like some charset issue with bazel? Am i right?

My toolchain configures:
cat **04_platforms/third_party/toolchains/aarch64-fsl-linux-sysroot.BUILD** 
```
package(default_visibility = ['//visibility:public'])

filegroup(
  name = 'sysroot',
  srcs = glob([
    '**',
  ]),
)
```

cat **04_platforms/third_party/toolchains/aarch64-fsl-linux.BUILD**
```
package(default_visibility = ['//visibility:public'])

filegroup(
  name = 'toolchain',
  srcs = glob([
    '**',
  ]),
)
```

cat **04_platforms/third_party/toolchains/toolchains.bzl**
```
add the following code in the toolchains function :(the toolchain is to big, so I change to my local path)

    if "aarch64-fsl-linux" not in native.existing_rules():
        native.new_local_repository(
            name = "aarch64-fsl-linux",
            build_file = Label("//third_party/toolchains:aarch64-fsl-linux.BUILD"),
            path = "/opt/fsl-auto/32.0/sysroots/x86_64-fslbsp-linux/",
        )

    if "aarch64-fsl-linux-sysroot" not in native.existing_rules():
        native.new_local_repository(
            name = "aarch64-fsl-linux-sysroot",
            build_file = Label("//third_party/toolchains:aarch64-fsl-linux-sysroot.BUILD"),
            path = "/opt/fsl-auto/32.0/sysroots/cortexa53-crypto-fsl-linux/",
        )
```

cat **04_platforms/bazel/platforms/BUILD**
```
platform(
    name = "s32g",
    constraint_values = [
        "@platforms//cpu:arm64e",
        "@platforms//os:linux",
    ],
)
```

cat **04_platforms/bazel/toolchain/toolchain.bzl**
```
def register_all_toolchains():
    native.register_toolchains(
        "//bazel/toolchain/aarch64-rpi3-linux-gnu:aarch64_linux_toolchain",
        "//bazel/toolchain/arm-cortex_a8-linux-gnueabihf:armv7_linux_toolchain",
        "//bazel/toolchain/aarch64-fsl-linux:arm64e_linux_toolchain",                           # register new toolchain
    )
```

cat **04_platforms/bazel/toolchain/aarch64-fsl-linux/cc_toolchain_config.bzl**
```
load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")
load("@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
    "feature",
    "flag_group",
    "flag_set",
    "tool_path",
)

all_link_actions = [
    ACTION_NAMES.cpp_link_executable,
    ACTION_NAMES.cpp_link_dynamic_library,
    ACTION_NAMES.cpp_link_nodeps_dynamic_library,
]

all_compile_actions = [
    ACTION_NAMES.assemble,
    ACTION_NAMES.c_compile,
    ACTION_NAMES.clif_match,
    ACTION_NAMES.cpp_compile,
    ACTION_NAMES.cpp_header_parsing,
    ACTION_NAMES.cpp_module_codegen,
    ACTION_NAMES.cpp_module_compile,
    ACTION_NAMES.linkstamp_compile,
    ACTION_NAMES.lto_backend,
    ACTION_NAMES.preprocess_assemble,
]

def _impl(ctx):
    tool_paths = [
        tool_path(
            name = "gcc",
            path = "wrappers/aarch64-fsl-linux-gcc",
        ),
        tool_path(
            name = "ld",
            path = "wrappers/aarch64-fsl-linux-gcc-ld",
        ),
        tool_path(
            name = "ar",
            path = "wrappers/aarch64-fsl-linux-ar",
        ),
        tool_path(
            name = "cpp",
            path = "wrappers/aarch64-fsl-linux-cpp",
        ),
        tool_path(
            name = "gcov",
            path = "wrappers/aarch64-fsl-linux-gcov",
        ),
        tool_path(
            name = "nm",
            path = "wrappers/aarch64-fsl-linux-nm",
        ),
        tool_path(
            name = "objdump",
            path = "wrappers/aarch64-fsl-linux-objdump",
        ),
        tool_path(
            name = "strip",
            path = "wrappers/aarch64-fsl-linux-strip",
        ),
    ]

    default_compiler_flags = feature(
        name = "default_compiler_flags",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = all_compile_actions,
                flag_groups = [
                    flag_group(
                        flags = [
                            "--sysroot=external/aarch64-fsl-linux-sysroot",
                            "-no-canonical-prefixes",
                            "-fno-canonical-system-headers",
                            "-Wno-builtin-macro-redefined",
                            "-D__DATE__=\"redacted\"",
                            "-D__TIMESTAMP__=\"redacted\"",
                            "-D__TIME__=\"redacted\"",
                        ],
                    ),
                ],
            ),
        ],
    )

    default_linker_flags = feature(
        name = "default_linker_flags",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = all_link_actions,
                flag_groups = ([
                    flag_group(
                        flags = [
                            "--sysroot=external/aarch64-fsl-linux-sysroot",
                            "-lstdc++",
                        ],
                    ),
                ]),
            ),
        ],
    )

    features = [
        default_compiler_flags,
        default_linker_flags,
    ]

    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        features = features,
        toolchain_identifier = "arm64e-toolchain",
        host_system_name = "local",
        target_system_name = "unknown",
        target_cpu = "unknown",
        target_libc = "unknown",
        compiler = "unknown",
        abi_version = "unknown",
        abi_libc_version = "unknown",
        tool_paths = tool_paths,
    )

cc_toolchain_config = rule(
    implementation = _impl,
    attrs = {},
    provides = [CcToolchainConfigInfo],
)
```

cat **04_platforms/bazel/toolchain/aarch64-fsl-linux/wrappers/wrapper**
```
#!/bin/bash
 
NAME=$(basename "$0")

TOOLCHAIN_BINDIR=external/aarch64-fsl-linux/usr/bin/aarch64-fsl-linux

exec "${TOOLCHAIN_BINDIR}"/"${NAME}" "$@"
```

cat **04_platforms/.bazelrc**
```
build:platform_build --incompatible_enable_cc_toolchain_resolution
build:rpi-platform --config=platform_build --platforms=//bazel/platforms:rpi
build:bbb-platform --config=platform_build --platforms=//bazel/platforms:bbb
build:s32g-platform --config=platform_build --platforms=//bazel/platforms:s32g    # add new platform 
```

**Comment by ltekieli** [comment]
```
/root/.cache/bazel/bazel_root/070a2d845f91c9901923bd1aab12f574/external/aarch64-fsl-linux/etc/ssl/certs/NetLock_Arany=Class_Gold=_Főtanúsítvány.pem (No such file or directory)
```

This usually means that the file is not available in the sandbox for the linking action.

I'm not sure what your hello example does exactly, but it seems it lacks the depnedency to ```aarch64-fsl-linux/etc/ssl/certs/NetLock_Arany=Class_Gold=_Főtanúsítvány.pem```.

**Comment by DamonChen2026** [comment]
HI, Itekieli:
thanks!
The hello example just include the std header iostream and then call the std::cout in the main function.
I use the CMake to build this example, and check the params for the compile options, I dont find anything difference.
And in the example, I dont know why need to link ths NetLock_Arany=Class_Gold=_Főtanúsítvány.pem ?

**Comment by DamonChen2026** [comment]
This usually means that the file is not available in the sandbox for the linking action. 

This file is under the toolchain, So ,how to intruduce this path to sandbox?

**Comment by ltekieli** [comment]
Can you share the toolchain you are using? I'm not sure why it requires openssl.

**Comment by DamonChen2026** [comment]
Sorry for later reply!!!
We use the yocto toolchain. 
The file is to big.

https://wetransfer.com/downloads/c42965771879af243ba061097667097220240402144015/8812acb439512b94ecaece55784656b320240402144039/eec12b?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

or try to download form this site:
http://downloads.yoctoproject.org/releases/yocto/yocto-4.1.2/toolchain/x86_64/poky-glibc-x86_64-core-image-sato-cortexa57-qemuarm64-toolchain-4.1.2.sh

thanks!!!

**Comment by ltekieli** [comment]
I used https://github.com/pziggo/bazel-toolchains-yocto and the toolchain works fine. Here's the setup:

**.bazelrc** 
```
build --incompatible_strict_action_env
build --incompatible_enable_cc_toolchain_resolution

build --verbose_failures

build:cortexa53 --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
build:cortexa53 --platforms=@cortexa53//bazel:platform-target
build:cortexa53 --extra_toolchains=@cortexa53//bazel/toolchain:cc-toolchain-target
```

**.bazelversion** 
```
6.5.0
```

**BUILD**
```
cc_binary(
    name = "simple_hello_cpp",
    srcs = ["simple_hello.cpp"],
)
```

**BUILD.cortexa53**
```
# Static build file for testing

filegroup(
    name = "target_sysroot_minimal",
    srcs = glob(
        [
            "sysroots/x86_64-fslbsp-linux/usr/lib/aarch64-fsl-linux/**",
            "sysroots/cortexa53-crypto-fsl-linux/lib/*.so*",
            "sysroots/cortexa53-crypto-fsl-linux/usr/include/**",
            "sysroots/cortexa53-crypto-fsl-linux/usr/lib/**/*.a",
            "sysroots/cortexa53-crypto-fsl-linux/usr/lib/**/*.o",
            "sysroots/cortexa53-crypto-fsl-linux/usr/lib/**/*.so*",
        ],
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "native_runtime",
    srcs = glob([
        "sysroots/x86_64-fslbsp-linux/lib/ld-*.so",
        "sysroots/x86_64-fslbsp-linux/lib/ld-linux*.so.*",
        "sysroots/x86_64-fslbsp-linux/lib/libc.so.*",
        "sysroots/x86_64-fslbsp-linux/lib/libdl.so.*",
        "sysroots/x86_64-fslbsp-linux/lib/libm.so.*",
        "sysroots/x86_64-fslbsp-linux/lib/libpthread.so.*",
        "sysroots/x86_64-fslbsp-linux/usr/lib/lib*.so.*",
        "sysroots/x86_64-fslbsp-linux/usr/libexec/aarch64-fsl-linux/**",
    ]),
)

filegroup(
    name = "gcc",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-g++",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-gcc",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cpp",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-cpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ar",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-ar",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ld",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-ld",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "nm",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-nm",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "objcopy",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-objcopy",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "objdump",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-objdump",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "strip",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-strip",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "as",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-as",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "addr2line",
    srcs = [
        ":native_runtime",
        "sysroots/x86_64-fslbsp-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-addr2line",
    ],
    visibility = ["//visibility:public"],
)
```

**simple_hello.cpp** 
```
#include <exception>
#include <iostream>

int main() {
    std::cout << "Hello!" << std::endl;

    try {
        throw std::invalid_argument( "test exception, good to be caught" );
    } catch (const std::exception& e) {
        std::cerr << "Exception caught: " << e.what() << std::endl;
    }

    return 0;
}
```

**WORKSPACE** 
```
workspace(
    name = "bazel-yocto",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "bazel_toolchains_yocto",
    sha256 = "cd2683c2252c3113719f49a7a3c15c3c90d0bdfa37a1e254db243fda308ca727",
    strip_prefix = "bazel-toolchains-yocto-0.0.4",
    url = "https://github.com/pziggo/bazel-toolchains-yocto/archive/refs/tags/v0.0.4.tar.gz",
)

load("@bazel_toolchains_yocto//yocto:repositories.bzl", "bazel_toolchains_yocto_dependencies")

bazel_toolchains_yocto_dependencies()

load("@bazel_toolchains_yocto//yocto:defs.bzl", "http_yocto_toolchain_archive", "http_yocto_toolchain_file", "local_yocto_toolchain")

http_yocto_toolchain_file(
    name = "cortexa53",
    build_file = "@//:BUILD.cortexa53",
    environment_setup = "environment-setup-cortexa53-crypto-fsl-linux",
    sha256 = "ff1fae95b67e42bde745f6ccb214ac819fc75c5c103363b3210b175ca1c73610",
    urls = [
        "file:///downloads/fsl-auto-glibc-x86_64-cortexa53-crypto-toolchain-32.0.sh",
    ],
)
```

**Comment by ltekieli** [comment]
And for your config, the problematic files can be excluded from the build:

**third_party/toolchains/aarch64-fsl-linux-sysroot.BUILD**
```
package(default_visibility = ['//visibility:public'])

filegroup(
  name = 'sysroot',
  srcs = glob(
    [
      '**',
    ],
  exclude =
    [
      "**/ca-certificates/**/*",
      "**/certs/**/*",
    ],
  ),
)

```

**third_party/toolchains/aarch64-fsl-linux.BUILD** 

```
package(default_visibility = ['//visibility:public'])

filegroup(
  name = 'toolchain',
  srcs = glob(
    [
      '**',
    ],
  exclude =
    [
      "**/ca-certificates/**/*",
      "**/certs/**/*",
    ],
  ),
)
```

Those globs are matching everything for simplicity, but should in the end just pick the stuff you really need.

**Comment by DamonChen2026** [comment]
OK， Thanks！
let me try this way!

**Comment by DamonChen2026** [comment]
HI Itekieli: 
It does work for the example. But when I add the proto file, and this need the protoc tools, then the log shows that the tool protoc is the aarch64 type, so it still failed.
the following is the compile logs:
damon@Zdrive:~/Work/Codes/bazel-yocto$ bazel build --config=cortexa53 -s //...
Starting local Bazel server and connecting to it...
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@cortexa53//bazel:platform-target, 
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@cortexa53//bazel:platform-target, 
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@cortexa53//bazel:platform-target
      ToolchainResolution:   Toolchain @@cortexa53//bazel/toolchain:cc-target is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Incompatible execution platform @@cortexa53//bazel:platform-target; mismatching values: x86_64
      ToolchainResolution:     Compatible execution platform @@local_config_platform//:host
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@cortexa53//bazel:platform-target:
      ToolchainResolution:   Selected @@cortexa53//bazel/toolchain:cc-target to run on execution platform @@local_config_platform//:host
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@local_config_platform//:host, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@cortexa53//bazel/toolchain:cc-target
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@local_config_platform//:host, 
INFO: ToolchainResolution: Target platform @@local_config_platform//:host: Selected execution platform @@cortexa53//bazel:platform-target, 
SUBCOMMAND: # @@com_google_protobuf_protoc_linux_aarch64//:protoc [action 'Executing genrule @@com_google_protobuf_protoc_linux_aarch64//:protoc [for tool]', configuration: a18f4f191bacc01b8d153fe26737aa7de5fe712698482a176fb4814f86500faa, execution platform: @@cortexa53//bazel:platform-target, mnemonic: Genrule]
(cd /home/damon/.cache/bazel/_bazel_damon/d21363b5d5c72367a0352d5ed85b4abf/execroot/bazel-yocto && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp external/com_google_protobuf_protoc_linux_aarch64/bin/protoc bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe && chmod +x bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe')
# Configuration: a18f4f191bacc01b8d153fe26737aa7de5fe712698482a176fb4814f86500faa
# Execution platform: @@cortexa53//bazel:platform-target
SUBCOMMAND: # //proto:simple_image_proto [action 'Generating Descriptor Set proto_library //proto:simple_image_proto', configuration: 8b5cc81254235e8092c95f5f649634643680f78467d0b8e558c156134574893a, execution platform: @@cortexa53//bazel:platform-target, mnemonic: GenProtoDescriptorSet]
(cd /home/damon/.cache/bazel/_bazel_damon/d21363b5d5c72367a0352d5ed85b4abf/execroot/bazel-yocto && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe --direct_dependencies proto/simple_image.proto '--direct_dependencies_violation_msg=%s is imported, but //proto:simple_image_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' '--descriptor_set_out=bazel-out/k8-fastbuild/bin/proto/simple_image_proto-descriptor-set.proto.bin' -I. --experimental_allow_proto3_optional proto/simple_image.proto)
# Configuration: 8b5cc81254235e8092c95f5f649634643680f78467d0b8e558c156134574893a
# Execution platform: @@cortexa53//bazel:platform-target
ERROR: /home/damon/Work/Codes/bazel-yocto/proto/BUILD:13:14: Generating Descriptor Set proto_library //proto:simple_image_proto failed: (Exit 2): protoc.exe failed: error executing GenProtoDescriptorSet command (from target //proto:simple_image_proto) 
  (cd /home/damon/.cache/bazel/_bazel_damon/d21363b5d5c72367a0352d5ed85b4abf/sandbox/linux-sandbox/2/execroot/bazel-yocto && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe --direct_dependencies proto/simple_image.proto '--direct_dependencies_violation_msg=%s is imported, but //proto:simple_image_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' '--descriptor_set_out=bazel-out/k8-fastbuild/bin/proto/simple_image_proto-descriptor-set.proto.bin' -I. --experimental_allow_proto3_optional proto/simple_image.proto)
# Configuration: 8b5cc81254235e8092c95f5f649634643680f78467d0b8e558c156134574893a
# Execution platform: @@cortexa53//bazel:platform-target

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe: 1: ELF��A@��@8: not found
bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe: 1: Syntax error: word unexpected (expecting ")")
Target //proto:simple_image_proto failed to build
INFO: Elapsed time: 52.944s, Critical Path: 0.05s
INFO: 3 processes: 2 internal, 1 linux-sandbox.
ERROR: Build did NOT complete successfully
damon@Zdrive:~/Work/Codes/bazel-yocto$ file bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe
bazel-out/k8-opt-exec-ST-efb817f568b6/bin/external/com_google_protobuf_protoc_linux_aarch64/protoc.exe: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=0191d94d0182b716c7aad921f3327b29be444ecc, stripped
damon@Zdrive:~/Work/Codes/bazel-yocto$ 

and the attachment is my project, can you help me to point out the issue?
it seems there are something about the toolchain still icorrect.
thanks!
[bazel-yocto.tar.gz](https://github.com/ltekieli/bazel_cross_compile/files/14846485/bazel-yocto.tar.gz)

**Comment by DamonChen2026** [comment]
ToolchainResolution: Selected @@cortexa53//bazel/toolchain:cc-target to run on execution platform @@local_config_platform//:host

I think may be something wrong in the envs when bazel to detect the toolchains. But I dont find where to set/change the envs.

**Comment by ltekieli** [comment]
Since protoc needs to be compiled for host target, you need to remove this line from your .bazelrc:
```
build:cortexa53 --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
```

**Comment by DamonChen2026** [comment]
I have added this flag, it didnt work.
I found the bazel_toolchains_yocto may be something wrong.
in this file: yocto/private/toolchain_template.bzl
cc_toolchain_config:
host_system_name = "{native_prefix}",  
and the "native_prefix" got from the OECORE_NATIVE_SYSROOT in the environment_setup file.
So, its value is x86_64-fslbsp-linux, 
I hard code to x86_64 host_system_name = "x86_64",   and then it works for the sample code with the protobuf.

Thanks!!!

**Comment by DamonChen2026** [comment]
HI Itekieli:
Although the above fix can pass the compile,but I checked the log, it seems that the toolchain still incorrect selected.

damon@in-dev-docker:/bazel-yocto$ bazel build --config=cortexa53 -s //...
DEBUG: /home/damon/.cache/bazel/_bazel_damon/de2e21614189902b1457bf2b9d5253fa/external/bazel_toolchains_yocto/yocto/private/sdk_utils.bzl:113:14: Get Env by key OECORE_TARGET_ARCH: aarch64 
DEBUG: /home/damon/.cache/bazel/_bazel_damon/de2e21614189902b1457bf2b9d5253fa/external/bazel_toolchains_yocto/yocto/private/sdk_utils.bzl:114:14: Update Value to arm64e
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@local_config_platform//:host, 
INFO: ToolchainResolution: Target platform @@local_config_platform//:host: Selected execution platform @@local_config_platform//:host, 
SUBCOMMAND: # @@com_google_protobuf_protoc_linux_x86_64//:protoc [action 'Executing genrule @@com_google_protobuf_protoc_linux_x86_64//:protoc [for tool]', configuration: 57e000854ef54bdb20e25ef8bc9bdf6a79db943c1f4b27152f04b33d1505face, execution platform: @@local_config_platform//:host, mnemonic: Genrule]
(cd /home/damon/.cache/bazel/_bazel_damon/de2e21614189902b1457bf2b9d5253fa/execroot/bazel-yocto && \
  exec env - \
    LD_LIBRARY_PATH=:/zark/lib \
    PATH=/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/zark \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp external/com_google_protobuf_protoc_linux_x86_64/bin/protoc bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf_protoc_linux_x86_64/protoc.exe && chmod +x bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf_protoc_linux_x86_64/protoc.exe')
# Configuration: 57e000854ef54bdb20e25ef8bc9bdf6a79db943c1f4b27152f04b33d1505face
# Execution platform: @@local_config_platform//:host
SUBCOMMAND: # //proto:simple_image_proto [action 'Generating Descriptor Set proto_library //proto:simple_image_proto', configuration: 3b56279ef6d9c94833e7e6054eb95b1d41e241a9053c85f438d56ae5e5aae4b2, execution platform: @@local_config_platform//:host, mnemonic: GenProtoDescriptorSet]
(cd /home/damon/.cache/bazel/_bazel_damon/de2e21614189902b1457bf2b9d5253fa/execroot/bazel-yocto && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    LD_LIBRARY_PATH=:/zark/lib \
    PATH=/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/zark \
  bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf_protoc_linux_x86_64/protoc.exe --direct_dependencies proto/simple_image.proto '--direct_dependencies_violation_msg=%s is imported, but //proto:simple_image_proto doesn'\''t directly depend on a proto_library that '\''srcs'\'' it.' '--descriptor_set_out=bazel-out/k8-fastbuild/bin/proto/simple_image_proto-descriptor-set.proto.bin' -I. --experimental_allow_proto3_optional proto/simple_image.proto)
# Configuration: 3b56279ef6d9c94833e7e6054eb95b1d41e241a9053c85f438d56ae5e5aae4b2
# Execution platform: @@local_config_platform//:host
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@cortexa53//bazel:platform-target
      ToolchainResolution:   Toolchain @@cortexa53//bazel/toolchain:cc-target is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Compatible execution platform @@local_config_platform//:host
      ToolchainResolution:   All execution platforms have been assigned a @@bazel_tools//tools/cpp:toolchain_type toolchain, stopping
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@cortexa53//bazel:platform-target:
      ToolchainResolution:   **Selected @@cortexa53//bazel/toolchain:cc-target to run on execution platform @@local_config_platform//:host**
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@local_config_platform//:host, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@cortexa53//bazel/toolchain:cc-target
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@local_config_platform//:host, 
INFO: ToolchainResolution: Performing resolution of @@bazel_tools//tools/cpp:toolchain_type for target platform @@cortexa53//bazel:platform-target
      ToolchainResolution:   Toolchain @@cortexa53//bazel/toolchain:cc-target is compatible with target plaform, searching for execution platforms:
      ToolchainResolution:     Compatible execution platform @@local_config_platform//:host
      ToolchainResolution:   All execution platforms have been assigned a @@bazel_tools//tools/cpp:toolchain_type toolchain, stopping
      ToolchainResolution: Recap of selected @@bazel_tools//tools/cpp:toolchain_type toolchains for target platform @@cortexa53//bazel:platform-target:
      ToolchainResolution:   **Selected @@cortexa53//bazel/toolchain:cc-target to run on execution platform @@local_config_platform//:host**
INFO: ToolchainResolution: Target platform @@cortexa53//bazel:platform-target: Selected execution platform @@local_config_platform//:host, type @@bazel_tools//tools/cpp:toolchain_type -> toolchain @@cortexa53//bazel/toolchain:cc-target
SUBCOMMAND: # //proto:simple_image_proto [action 'Generating proto_library //proto:simple_image_proto', configuration: 3b56279ef6d9c94833e7e6054eb95b1d41e241a9053c85f438d56ae5e5aae4b2, execution platform: @@local_config_platform//:host, mnemonic: GenProto]
(cd /home/damon/.cache/bazel/_bazel_damon/de2e21614189902b1457bf2b9d5253fa/execroot/bazel-yocto && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1

**Comment by ltekieli** [comment]
> I have added this flag, it didnt work. I found the bazel_toolchains_yocto may be something wrong. in this file: yocto/private/toolchain_template.bzl cc_toolchain_config: host_system_name = "{native_prefix}", and the "native_prefix" got from the OECORE_NATIVE_SYSROOT in the environment_setup file. So, its value is x86_64-fslbsp-linux, I hard code to x86_64 host_system_name = "x86_64", and then it works for the sample code with the protobuf.
> 
> Thanks!!!

You need to remove this flag.

**Comment by DamonChen2026** [comment]
I have changed these two flags:
-    host_system_name = "{native_prefix}",
-    target_system_name = "{target_prefix}",
+    host_system_name = "local",
+    target_system_name = "unknown"

but the toolchain still incorrect selected!

**Comment by ltekieli** [comment]
I've added a small example of using yocto toolchain and proto together. Have a look:
- https://github.com/ltekieli/bazel-recipes/tree/master/yocto_proto

I'll close this issue as it's not really related anymore to the repo. This repo is anyways just a small backup for the blog post :)
